[2024-01-09T17:17:29.506+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-12-02T07:00:00+00:00 [queued]>
[2024-01-09T17:17:29.518+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-12-02T07:00:00+00:00 [queued]>
[2024-01-09T17:17:29.518+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-09T17:17:29.534+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 07:00:00+00:00
[2024-01-09T17:17:29.544+0000] {standard_task_runner.py:60} INFO - Started process 163 to run task
[2024-01-09T17:17:29.549+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2023-12-02T07:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcp.py', '--cfg-path', '/tmp/tmpv1qk51nw']
[2024-01-09T17:17:29.554+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask local_to_gcs_task
[2024-01-09T17:17:29.623+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-12-02T07:00:00+00:00 [running]> on host f5de67cb9685
[2024-01-09T17:17:29.684+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-01-09T17:17:29.731+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T07:00:00+00:00'
[2024-01-09T17:17:29.843+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcp_script.py", line 21, in upload_to_gcs
    with open(local_file, 'rb') as f:
AttributeError: __enter__
[2024-01-09T17:17:29.854+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20231202T070000, start_date=20240109T171729, end_date=20240109T171729
[2024-01-09T17:17:29.868+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 98 for task local_to_gcs_task (__enter__; 163)
[2024-01-09T17:17:29.882+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-09T17:17:29.915+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-10T00:16:25.442+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-12-02T07:00:00+00:00 [queued]>
[2024-01-10T00:16:25.473+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-12-02T07:00:00+00:00 [queued]>
[2024-01-10T00:16:25.473+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-10T00:16:25.494+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 07:00:00+00:00
[2024-01-10T00:16:25.505+0000] {standard_task_runner.py:60} INFO - Started process 6867 to run task
[2024-01-10T00:16:25.511+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2023-12-02T07:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcp.py', '--cfg-path', '/tmp/tmp8fdbh2a1']
[2024-01-10T00:16:25.518+0000] {standard_task_runner.py:88} INFO - Job 143: Subtask local_to_gcs_task
[2024-01-10T00:16:25.586+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2023-12-02T07:00:00+00:00 [running]> on host f5de67cb9685
[2024-01-10T00:16:25.646+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-01-10T00:16:25.691+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T07:00:00+00:00'
[2024-01-10T00:16:25.804+0000] {ingest_data_gcp_script.py:24} INFO - Starting upload of /opt/***/input_2023-12.parquet to raw/yellow_tripdata_2023_12.parquet
[2024-01-10T00:16:26.230+0000] {ingest_data_gcp_script.py:29} INFO - Finished upload of /opt/***/input_2023-12.parquet to raw/yellow_tripdata_2023_12.parquet
[2024-01-10T00:16:26.230+0000] {python.py:201} INFO - Done. Returned value was: https://storage.googleapis.com/dtc-de-project1-terra-bucket/raw/yellow_tripdata_2023_12.parquet
[2024-01-10T00:16:26.272+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20231202T070000, start_date=20240110T001625, end_date=20240110T001626
[2024-01-10T00:16:26.328+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-10T00:16:26.364+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
